version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: db_nisit_web
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
