version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: db_nisit_web
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nisit_web
    ports:
      - "3306:3306"
